### ISSUE TITLE
bug: Getting error jq: error (at monokle-1707400873136.sarif:0): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by nsalfos** [sett-and-hive/sarif-to-comment-action#267]
### Version

2.0.1

### Current Behavior

im testing Monokle GHA and it does creat a SARIF file. 
but when using `sarif-to-comment-action` im getting the error `jq: error (at monokle-1707485394343.sarif:0): Cannot iterate over null (null)`

### Expected Behavior

i would expect it to post the findings from monokle as c omment on the PR

### Steps to Reproduce

pull any helm chart locally  (i used  bitnami/airflow ) 
<details>
<summary>Pull Chart</summary>

`helm pull bitnami/airflow --untar`

</details>

in root dir create the `monokle.validation.yaml` rules file:

<details>

<summary>monokle.validation.yaml</summary>

```
plugins:
  yaml-syntax: true
  open-policy-agent: true
  kubernetes-schema: true
  labels: false
rules:
  yaml-syntax/no-bad-alias: "warn"
  yaml-syntax/no-bad-directive: false
  open-policy-agent/no-latest-image: "err"
  open-policy-agent/cpu-limit: "err"
  open-policy-agent/memory-limit: "err"
  open-policy-agent/memory-request: "err"
  practices/no-low-user-id: true
  practices/no-low-group-id: true
```

</details>

<details>
<summary>GH Workflow</summary>

```
name: Lint and Test Charts

on: pull_request
permissions: write-all

jobs:
  validate:
    
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - id: bake
        name: Bake chart
        uses: azure/k8s-bake@v2.4
        with:
          renderEngine: "helm"
          helmChart: "./helm-charts/airflow"

      - id: validate
        name: Validate Manifest
        uses: kubeshop/monokle-action@v0.3.2
        continue-on-error: true
        with:
          path: ${{ steps.bake.outputs.manifestsBundle }}
          config: <path-to-file>/monokle.validation.yaml.    # Update this path

      - name: Test for file.   # this is not really needed, using it as a debug.
        run: | 
          ls
          cat ${{ steps.validate.outputs.sarif }}
          jq . ${{ steps.validate.outputs.sarif }}
      
      - name: Post SARIF findings in the issue
        uses: sett-and-hive/sarif-to-comment-action@v2.0.1        
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          pr-number: ${{ github.event.number }}
          sarif-file: ${{ steps.validate.outputs.sarif }}
          title: "Security scanning results"
          odc-sarif: false
          dry-run: false

```

</details>

Run any draft PR against the branch to make the workflow execute. 

### Additional Information

With above rules file monokle should return this report for bitnami/airflow

```
Run kubernetes-schema (26 problems)
Run yaml-syntax
Run open-policy-agent (39 problems)
```
