### ISSUE TITLE
bug: CodeGuru Reviewer sarif error

### ISSUE THREAD

**Issue by oc-stephen-bennett** [sett-and-hive/sarif-to-comment-action#341]
### Version

2.0.1

### Current Behavior

Run sett-and-hive/sarif-to-comment-action@v2.0.1
/usr/bin/docker run --name fcdc24d6708d8bdc2d4fbc83b4dadfc7bd2ffa_b66988 --label fcdc24 --workdir /github/workspace --rm -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "INPUT_TITLE" -e "INPUT_SARIF-FILE" -e "INPUT_TOKEN" -e "INPUT_REPOSITORY" -e "INPUT_BRANCH" -e "INPUT_PR-NUMBER" -e "INPUT_SHOW-RULE-DETAILS" -e "INPUT_DRY-RUN" -e "INPUT_ODC-SARIF" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKS
Convert SARIF file /github/workspace/codeguru-results.sarif.json
npm WARN exec The following package was not found and will be installed: @security-alert/sarif-to-comment@1.10.10
  post comment to GitHub issue/pull requests
  Usage
    $ npx @security-alert/sarif-to-comment <sarif-file-path>
 
  Inputs
    <sarif-file-path> Path to sarif file path
 
  Options
    --dryRun                      Dry-Run when it is enabled
    --token                       GitHub Token, or support environment variables - GITHUB_TOKEN=xxx
    --action                      Authentication mode for the token, defaults to PAT, if set, switches to Github Action
    --ruleDetails                 Include rule details in the markdown, might be too big for Github's API, defaults to false
    --simple                      Simplify the output to only give findings grouped by rule, adds helpURI if present
    --severity                    Filter output issues by their severity level, warning, error, note, none, set flag for each level      
    --failon                      Throw an exit error code 1 if an issue with that level was detected, warning, error, note, none, or all, set flag for each, NOT affected by severity filtering
    --title                       Specify a comment title for the report, optional
    --no-suppressedResults        Don't include suppressed results, that are in SARIF suppressions
    --commentUrl                  Post to comment URL. e.g. https://github.com/owner/repo/issues/85
    --sarifContentOwner           GitHub Owner name of sarif content result.  e.g. "owner"
    --sarifContentRepo            GitHub Repository name of sarif content result. e.g. "repo"
    --sarifContentBranch          GitHub Repository branch name of sarif content result. e.g. "master"
    --sarifContentSourceRoot      Base path to sarif scanned source. You can set CodeQL's sourceLocationPrefix as relative value if necessary
  
  Examples
    # DryRun and preview it!
    $ GITHUB_TOKEN=xxx npx @security-alert/sarif-to-comment --commentUrl "https://github.com/owner/repo/issues/1" --sarifContentOwner "owner" --sarifContentRepo "repo" --sarifContentBranch "master" "./codeql_result.sarif"
    # Post It
    $ GITHUB_TOKEN=xxx npx @security-alert/sarif-to-comment --commentUrl "https://github.com/owner/repo/issues/1" --sarifContentOwner "owner" --sarifContentRepo "repo" --sarifContentBranch "master" "./codeql_result.sarif"
    # Set base path
    $ GITHUB_TOKEN=xxx npx @security-alert/sarif-to-comment --commentUrl "https://github.com/owner/another/issues/1" --sarifContentOwner "owner" --sarifContentRepo "repo" --sarifContentBranch "develop" --sarifContentSourceRoot "./basepath" "./codeql_result.sarif"
    # use HEAD sha for link
    $ GITHUB_TOKEN=xxx npx @security-alert/sarif-to-comment --commentUrl "https://github.com/owner/another/issues/1" --sarifContentOwner "owner" --sarifContentRepo "repo" ---sarifContentBranch `git rev-parse HEAD` "./codeql_result.sarif"

### Expected Behavior

Add output to pull request page

### Steps to Reproduce

```
jobs:
  codeguru:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS credentials
      id: iam-role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.CODE_GURU_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CODE_GURO_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      with:
        s3_bucket: {{ secrets.s3_codeguru }}

    - name: Post findings to pull request
      uses: sett-and-hive/sarif-to-comment-action@v2.0.1
      with:
        title: CodeGuru Reviewer Findings
        sarif-file: /github/workspace/codeguru-results.sarif.json
        token: ${{ secrets.BYPASS_TOKEN }}
        repository: ${{ github.repository }}
        branch: ${{ github.head_ref }}
        pr-number: ${{ github.event.number }}
```

### Additional Information

codeguru-reviewer doesnt give any options for output except for 

```
SARIF persisted to /github/workspace/codeguru-results.sarif.json
```
no sure if that fixed .json at the end causes the error, as the lack of clear output from the action
